language: java
jdk:
  - openjdk8

branches:
  only:
    - master

##
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
    #  gradle 버전 변경
    - sudo wget https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
    - sudo unzip -qq gradle-4.10.2-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.10.2
    - export PATH=$GRADLE_HOME/bin:$PATH
    - gradle -version
    - gradle wrap
    - chmod +x ./gradlew  # gradlew 실행 권한 부여 : Permission denied 에러 예방

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hdo03072@gmail.com