language: java
jdk:
  - openjdk8

branches:
  only:
    - master

##
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
    #  gradle 버전 변경
    - gradlew wrapper --gradle-version 4.10.2
    - chmod +x ./gradlew  # gradlew 실행 권한 부여 : Permission denied 에러 예방

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hdo03072@gmail.com